/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavigatorDrawer: typeof import('./components/NavigatorDrawer.vue')['default']
    RegistrationStudent: typeof import('./components/RegistrationStudent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentsList: typeof import('./components/StudentsList.vue')['default']
  }
}
